#!/bin/bash

# Save current directory, as it is used by ibuild to find the package's build.plist
PACKAGE_ROOT=$(pwd)

# Go to ibuild root
cd $(dirname "$0")

# Run ibuild, passing arguments
PACKAGE_ROOT=$PACKAGE_ROOT swift run ibuild $@